name: domain
description: "A pure Dart package for domain logic."
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.24.0